function ui_surf_x(source, event, test_range_start, test_mode, ...
    test_step, TH_NF_1HZ, sch, test_comp_name, all_component_gain, all_cumu_gain, all_p1db_in, ...
    all_iip3, all_nf, right_limit, right_base_limit)
    
    global my_ui_table;
    global txt;

    % snap to appropriate values
    source.Value = floor(source.Value + .5);
    
    % redraw label
    alteration = test_range_start+source.Value*test_step;
    delete(txt);
    txt = uicontrol('Style','text', 'Units', 'Normalized', ...
    'Position',[.6, .1, .3, .04],...
    'String', sprintf('%s Alteration: %.4f', test_mode, alteration));
    
    % TABLE
    % data
    row_names = {'Comp. Gain (dB)', 'Cumu. Gain (dB)', 'Input P1dB (dBm)', 'Output P1dB (dBm)' ...
        'Input IP3 (dBm)', 'Output IP3 (dBm)', 'Input N. Figure (dB)',  'Output N. Floor-1HZ (dBm)', 'Output N. Figure'};
    i = source.Value + 1; 
    comp_out_nfigure = (all_nf(i, :) + all_cumu_gain(i, :));
    comp_out_nfloor = TH_NF_1HZ + (all_nf(i, :) + all_cumu_gain(i, :));
    comp_out_p1db = all_p1db_in(i, :) + (all_cumu_gain(i, :)-1);
    comp_out_ip3 = all_iip3(i, :) + all_cumu_gain(i, :);
    dyn_range = right_base_limit - all_nf(:,end)' + 174;
    
    t = table(all_component_gain(i, :)', all_cumu_gain(i, :)', ... 
        all_p1db_in(i, :)', comp_out_p1db', all_iip3(i, :)', comp_out_ip3', ...
        all_nf(i, :)', comp_out_nfloor', ...
        comp_out_nfigure');
    
    %end_col_names = {'Cumu. Gain (dB)', 'Input P1dB (dBm)', 'Output P1dB (dBm)' ...
    %    'Input IP3 (dBm)', 'Output IP3 (dBm)', 'Input N. Figure (dB)',  'Output N. Floor-1HZ (dBm)', 'Output N. Figure'};
    
    end_col_names = {'Cumu. Gain (dB)', 'Input P1dB (dBm)' ...
        'Input IP3 (dBm)', 'Input N. Figure (dB)', 'Dyn Range', 'Base Limit'};

%         end_t = table(all_cumu_gain(i, end), ... 
%         all_p1db_in(i, end), comp_out_p1db(end), all_iip3(i, end), comp_out_ip3(end), ...
%         all_nf(i, end), comp_out_nfloor(end), ...
%         comp_out_nfigure(end));
    
    end_t = table(all_cumu_gain(i, end), ... 
        all_p1db_in(i, end), all_iip3(i, end), ...
        all_nf(i, end), dyn_range(i), right_base_limit(i));
    
    % title
    uicontrol('Style','text', 'Units', 'Normalized', ...
    'Position',[.1, .45, .8, .04],...
    'FontWeight', 'bold', 'String', ...
    sprintf('Cascaded System Data for %s %s of %.4f', ...
    test_comp_name, test_mode, alteration));

    % Redraw table
    delete(my_ui_table);
    my_ui_table = uitable('Data',t{:,:}','ColumnName', sch,...
        'RowName',row_names,'Units', 'Normalized', 'Position',[.1, .15 , .8, .3]);
    
    my_ui_table = uitable('Data',end_t{:,:},'ColumnName', end_col_names,...
            'RowName',{'Board'},'Units', 'Normalized', 'Position',[.1, .045 , .4 , .08]);
        
end
    